### PR TITLE
Update fuzzy-finder.cson

### PR DESCRIPTION
**Pull request by Martaaa96**
.

### Requirements

* Filling out the template is required. Any pull request that does not include enough information to be reviewed in a timely manner may be closed at the maintainers' discretion.
* All new code requires tests to ensure against regressions

### CODE REVIEW

**Comment by Martak96** [comment]
.

**Comment by Martaaa96** [comment]
Build system information
Build language: objective-c
git.checkout
6.00s$ git clone --depth=50 --branch=v0.83.0 git://github.com/atom/fuzzy-finder.git atom/fuzzy-finder
rvm
2.00s$ rvm use default
0.00s0.00s$ ruby --version
ruby 2.0.0p481 (2014-05-08 revision 45883) [x86_64-darwin13.1.0]
$ rvm --version
rvm 1.25.33 (stable) by Wayne E. Seguin <wayneeseguin@gmail.com>, Michal Papis <mpapis@gmail.com> [https://rvm.io/]
$ bundle --version
Bundler version 1.7.4
announce
$ xcodebuild -version -sdk
112.00s$ curl -s https://raw.githubusercontent.com/atom/ci/master/build-package.sh | sh
Downloading latest Atom release...
Using Atom version:
0.194.0
Downloading package dependencies...
Installing modules ✓
Running specs...
[575:0430/172258:INFO:renderer_main.cc(212)] Renderer process started
[573:0430/172302:INFO:CONSOLE(59)] "Window load time: 2358ms", source: file:///Users/travis/build/atom/fuzzy-finder/atom/Atom.app/Contents/Resources/app.asar/static/index.js (59)
..............................................
Finished in 24.441 seconds
46 tests, 289 assertions, 0 failures, 0 skipped
Tests passed
The command "curl -s https://raw.githubusercontent.com/atom/ci/master/build-package.sh | sh" exited with 0.
Done. Your build exited with 0.

**Comment by Martaaa96** [comment]
> .
> 
> ### Requirements
> * Filling out the template is required. Any pull request that does not include enough information to be reviewed in a timely manner may be closed at the maintainers' discretion.
> * All new code requires tests to ensure against regressions
> 
> ### Description of the Change
> ### Alternate Designs
> ### Benefits
> ### Possible Drawbacks
> ### Applicable Issues

**Review by Martaaa96 — COMMENTED** [review]
# Configuration for probot-no-response - https://github.com/probot/no-response

# Number of days of inactivity before an issue is closed for lack of response
daysUntilClose: 180

# Label requiring a response
responseRequiredLabel: more-information-needed

# Comment to post when closing an issue for lack of response. Set to `false` to disable.
closeComment: >
  This issue has been automatically closed because there has been no response
  to our request for more information from the original author. With only the
  information that is currently in the issue, we don't have enough information
  to take action. Please reach out if you have or find the answers we need so
  that we can investigate further.

**Comment by Martaaa96** [comment]
Kaczor.marta96@gmail.com
Martaaa96:patch-1

**Pull request closed without merging**
