### PR TITLE
Add logic to consume file-icons service

### PR DESCRIPTION
**Pull request by Alhadis**
This PR is largely modelled off @acontreras89's work in the `tree-view` package. It uses the services API to display file-icons, giving packages a chance to customise them in a clean manner.

I've added two simple specs to ward off regressions, although I wasn't sure if they were necessary or not.

### CODE REVIEW

**Comment by Alhadis** [comment]
/cc @lee-dohm 

As with atom/tabs#319, I've made sure packages can supply multiple classes if needed.

**Comment by lee-dohm** [comment]
I was out sick the last couple days and I'm a bit behind. I'll be taking a look here later this week.

**Comment by Alhadis** [comment]
Whoops, lint.



That image is funny because it also reflects my current destitute state of unemployment. :D

**Comment by lee-dohm** [comment]
Looks good to me! Thanks :grinning:

**Pull request merged**
