### PR TITLE
Fix excluding VCS ignored paths based on the flag in core settings when ripgrep is enabled

### PR DESCRIPTION
**Pull request by nikazooz**
### Description of the Change

This fixes a bug when experimental fast mode that uses ripgrep is enabled. Since excluding VCS ignored paths is the default behavior of ripgrep, option to not ignore them was not being passed when needed.

### Alternate Designs

N/A

### Benefits

Excluding VCS ignored paths from fuzzy search will work a bit more consistently when using ripgrep.

### Possible Drawbacks

N/A

### Applicable Issues

N/A

### CODE REVIEW

**Comment by 50Wliu** [comment]
Thanks @nikazooz! Can you please add a test for this to make sure it doesn't regress in the future?

**Comment by nikazooz** [comment]
@50Wliu I don't have much experience with writing tests for atom packages, but this should cover the case this PR solves. I'm open to suggestions for improvement if you have any :slightly_smiling_face:

**Comment by nikazooz** [comment]
Glad I was able to help 🙂
Thank you all for your work on this editor!

**Comment by 50Wliu** [comment]
Travis is having rate limit issues, so I think this is fine to merge.

**Pull request merged**
