### PR TITLE
fix split openning a pane from fuzzy finder view

### PR DESCRIPTION
**Pull request by joseramonc**
fix atom/atom#11192

### CODE REVIEW

**Comment by 50Wliu** [comment]
@joseramonc Please update the specs to correspond to this change.  Thanks!

**Comment by joseramonc** [comment]
@50Wliu Sorry, I have updated this pull request with the fixed specs too

**Comment by 50Wliu** [comment]
Awesome, thanks.  This looks good to me - /cc @atom/feedback.

**Comment by lee-dohm** [comment]
@joseramonc Thanks for the effort you put in on this and I apologize that it has taken this long for us to get to looking at your PR. It seems some time between when you submitted this PR and now (Atom v1.11.2) this was fixed. Because of this, I'm going to close this PR.

Thanks again for your time and interest in Atom!

**Pull request closed without merging**
