### PR TITLE
Preview selected files in list #5

### PR DESCRIPTION
**Pull request by neilthawani**
This PR is a clone of @jwuwork's contribution in https://github.com/atom/fuzzy-finder/pull/113 with the merge issues addressed.

Copy/paste of their PR details:
Ok folks, you asked for it. Here is the new feature for previewing selected files.

To enable this feature, go into fuzzy-finder Settings and check the new "Preview Selection" option:

image

Obviously, this works best if you have "Use Preview Tabs" option turned on from the tab package Settings.

### CODE REVIEW

**Comment by 50Wliu** [comment]
@neilthawani can you please take a look at the spec failure?

**Comment by slikk66** [comment]
Tried to sort this out, but having weird issue where my fork says it has merge conflicts.. I think all that needs to be added to ./lib/fuzzy-finder-view.js is:

```
diff --git a/lib/fuzzy-finder-view.js b/lib/fuzzy-finder-view.js
index d570f43..784b9d4 100644
--- a/lib/fuzzy-finder-view.js
+++ b/lib/fuzzy-finder-view.js
@@ -282,6 +282,11 @@ export default class FuzzyFinderView {
     }
   }

+  setMaxItems (maxCount) {
+    this.selectListView.setMaxItems(maxCount)
+    return maxCount
+  }
+
```

**Comment by neilthawani** [comment]
Well. Not sure what to do now. Sorry for the messy commits - all I wanted was a new feature.

**Comment by khalilgharbaoui** [comment]
?

**Comment by lee-dohm** [comment]
Upon reviewing with the team today, we've decided that we don't want to own this functionality because of the various performance and stability impacts that it could have on the fuzzy-finder package. For example, what if you type some characters or select files that match the data files in a particular directory that are 5GB each? For this reason, we're not going to accept this PR and we're closing the related issues.

However, we did discuss the possibility of someone creating a [provided service](https://flight-manual.atom.io/behind-atom/sections/interacting-with-other-packages-via-services/) that could allow other community packages to integrate with fuzzy-finder to provide this behavior. We would be open to reviewing an [RFC](https://github.com/atom/atom/blob/master/docs/rfcs/000-template.md) for a design of this proposed service in atom/fuzzy-finder. If anyone is interested in working on this, please open a new issue for the RFC for review by the maintainer team.

Thanks for your hard work and desire to make Atom better.

**Pull request closed without merging**
